// Package espn provides an HTTP client for the public ESPN API.
//
//nolint:revive
package espn

// Code generated from the Python ESPN client registry (SPORT_NAMES / LEAGUE_INFO). DO NOT EDIT.
// 17 sports, 139 leagues discovered from the ESPN v2/v3 WADL.

// LeagueMeta holds the display name and abbreviation for a league slug.
type LeagueMeta struct {
	Name         string
	Abbreviation string
}

// SportNames maps sport slug to display name (17 sports).
var SportNames = map[string]string{
	"australian-football": "Australian Football",
	"baseball":            "Baseball",
	"basketball":          "Basketball",
	"cricket":             "Cricket",
	"field-hockey":        "Field Hockey",
	"football":            "Football",
	"golf":                "Golf",
	"hockey":              "Hockey",
	"lacrosse":            "Lacrosse",
	"mma":                 "Mixed Martial Arts",
	"racing":              "Racing",
	"rugby":               "Rugby",
	"rugby-league":        "Rugby League",
	"soccer":              "Soccer",
	"tennis":              "Tennis",
	"volleyball":          "Volleyball",
	"water-polo":          "Water Polo",
}

// LeagueInfo maps league slug to its metadata (139 leagues).
var LeagueInfo = map[string]LeagueMeta{
	"afl":                         {Name: "AFL", Abbreviation: "AFL"},
	"caribbean-series":            {Name: "Caribbean Series", Abbreviation: "CAR"},
	"college-baseball":            {Name: "NCAA Baseball", Abbreviation: "NCAAB"},
	"college-softball":            {Name: "NCAA Softball", Abbreviation: "NCAAS"},
	"dominican-winter-league":     {Name: "Dominican Winter League", Abbreviation: "DWL"},
	"llb":                         {Name: "Little League Baseball", Abbreviation: "LLB"},
	"lls":                         {Name: "Little League Softball", Abbreviation: "LLS"},
	"mexican-winter-league":       {Name: "Mexican League", Abbreviation: "MLM"},
	"mlb":                         {Name: "Major League Baseball", Abbreviation: "MLB"},
	"olympics-baseball":           {Name: "Olympics Men's Baseball", Abbreviation: "OLY"},
	"puerto-rican-winter-league":  {Name: "Puerto Rican Winter League", Abbreviation: "PRWL"},
	"venezuelan-winter-league":    {Name: "Venezuelan Winter League", Abbreviation: "VWL"},
	"world-baseball-classic":      {Name: "World Baseball Classic", Abbreviation: "WBC"},
	"fiba":                        {Name: "FIBA World Cup", Abbreviation: "FIBA"},
	"mens-college-basketball":     {Name: "NCAA Men's Basketball", Abbreviation: "NCAAM"},
	"mens-olympics-basketball":    {Name: "Olympics Men's Basketball", Abbreviation: "OLY"},
	"nba":                         {Name: "National Basketball Association", Abbreviation: "NBA"},
	"nba-development":             {Name: "NBA G League", Abbreviation: "GLEA"},
	"nba-summer-california":       {Name: "NBA California Classic Summer League", Abbreviation: "NBASL"},
	"nba-summer-golden-state":     {Name: "Golden State Summer League", Abbreviation: "GSSL"},
	"nba-summer-las-vegas":        {Name: "Las Vegas Summer League", Abbreviation: "LVSL"},
	"nba-summer-orlando":          {Name: "Orlando Summer League", Abbreviation: "OSL"},
	"nba-summer-sacramento":       {Name: "Sacramento Summer League", Abbreviation: "SASL"},
	"nba-summer-utah":             {Name: "Salt Lake City Summer League", Abbreviation: "SLSL"},
	"nbl":                         {Name: "National Basketball League", Abbreviation: "NBL"},
	"wnba":                        {Name: "Women's National Basketball Association", Abbreviation: "WNBA"},
	"womens-college-basketball":   {Name: "NCAA Women's Basketball", Abbreviation: "NCAAW"},
	"womens-olympics-basketball":  {Name: "Olympics Women's Basketball", Abbreviation: "OLY"},
	"womens-college-field-hockey": {Name: "NCAA Women's Field Hockey", Abbreviation: "NCAAFH"},
	"cfl":                         {Name: "Canadian Football League", Abbreviation: "CFL"},
	"college-football":            {Name: "NCAA Football", Abbreviation: "NCAAF"},
	"nfl":                         {Name: "National Football League", Abbreviation: "NFL"},
	"ufl":                         {Name: "United Football League", Abbreviation: "UFL"},
	"xfl":                         {Name: "XFL", Abbreviation: "XFL"},
	"champions-tour":              {Name: "PGA TOUR Champions", Abbreviation: "CHAMP"},
	"eur":                         {Name: "DP World Tour", Abbreviation: "DP"},
	"liv":                         {Name: "LIV Golf Invitational Series", Abbreviation: "LIV"},
	"lpga":                        {Name: "Ladies Pro Golf Association", Abbreviation: "LPGA"},
	"mens-olympics-golf":          {Name: "Olympic Golf - Men", Abbreviation: "OLY"},
	"ntw":                         {Name: "Korn Ferry Tour", Abbreviation: "KFT"},
	"pga":                         {Name: "PGA TOUR", Abbreviation: "PGA"},
	"tgl":                         {Name: "TGL", Abbreviation: "TGL"},
	"womens-olympics-golf":        {Name: "Olympic Golf - Women", Abbreviation: "OLY"},
	"hockey-world-cup":            {Name: "World Cup of Hockey", Abbreviation: "WCOH"},
	"mens-college-hockey":         {Name: "NCAA Men's Ice Hockey", Abbreviation: "NCAAH"},
	"nhl":                         {Name: "National Hockey League", Abbreviation: "NHL"},
	"olympics-mens-ice-hockey":    {Name: "Men's Ice Hockey Olympics", Abbreviation: "OLY"},
	"olympics-womens-ice-hockey":  {Name: "Women's Ice Hockey Olympics", Abbreviation: "OLY"},
	"womens-college-hockey":       {Name: "NCAA Women's Hockey", Abbreviation: "NCAAWH"},
	"mens-college-lacrosse":       {Name: "NCAA Men's Lacrosse", Abbreviation: "NCAML"},
	"nll":                         {Name: "National Lacrosse League", Abbreviation: "NLL"},
	"pll":                         {Name: "Premier Lacrosse League", Abbreviation: "PLL"},
	"womens-college-lacrosse":     {Name: "NCAA Women's Lacrosse", Abbreviation: "NCAWL"},
	"absolute":                    {Name: "Absolute Championship Berkut", Abbreviation: "ACB"},
	"affliction":                  {Name: "Affliction", Abbreviation: "AFF"},
	"bang-fighting":               {Name: "Bang Fighting Championships", Abbreviation: "BFC"},
	"banni-fight":                 {Name: "Banni Fight Combat", Abbreviation: "BFC"},
	"banzay":                      {Name: "Banzay Fight Championship", Abbreviation: "BZY"},
	"barracao":                    {Name: "Barracao Fight Championship", Abbreviation: "BFC"},
	"battlezone":                  {Name: "Battlezone Fighting Championships", Abbreviation: "BZN"},
	"bellator":                    {Name: "Bellator Fighting Championship", Abbreviation: "BEL"},
	"benevides":                   {Name: "Benevides Fight Championship", Abbreviation: "BFG"},
	"big-fight":                   {Name: "Big Fight Champions", Abbreviation: "BFC"},
	"blackout":                    {Name: "Blackout Fighting Championship", Abbreviation: "BOF"},
	"bosnia":                      {Name: "Bosnia Fight Championship", Abbreviation: "BFC"},
	"boxe":                        {Name: "Boxe Fight Combat", Abbreviation: "BXE"},
	"brazilian-freestyle":         {Name: "Brazilian Freestyle Circuit", Abbreviation: "BRC"},
	"budo":                        {Name: "Budo Fighting Championships", Abbreviation: "BDO"},
	"cage-warriors":               {Name: "Cage Warriors Fighting Championship", Abbreviation: "CW"},
	"dream":                       {Name: "Dream", Abbreviation: "DRM"},
	"fng":                         {Name: "Fight Nights Global", Abbreviation: "FNG"},
	"ifc":                         {Name: "Invicta FC", Abbreviation: "IFC"},
	"ifl":                         {Name: "International Fight League", Abbreviation: "IFL"},
	"k1":                          {Name: "K-1", Abbreviation: "K1"},
	"ksw":                         {Name: "Konfrontacja Sztuk Walki", Abbreviation: "KSW"},
	"lfa":                         {Name: "Legacy Fighting Alliance", Abbreviation: "LFA"},
	"lfc":                         {Name: "Legacy Fighting Championship", Abbreviation: "LFC"},
	"m1":                          {Name: "M-1 Mix-Fight Championship", Abbreviation: "M1"},
	"f1":                          {Name: "Formula 1", Abbreviation: "F1"},
	"irl":                         {Name: "IndyCar Series", Abbreviation: "INDY"},
	"nascar-premier":              {Name: "NASCAR Cup Series", Abbreviation: "CUP"},
	"nascar-secondary":            {Name: "NASCAR O'Reilly Auto Parts Series", Abbreviation: "XFN"},
	"nascar-truck":                {Name: "NASCAR Truck Series", Abbreviation: "TRUCK"},
	"268565":                      {Name: "British and Irish Lions Tour", Abbreviation: "BILT"},
	"164205":                      {Name: "Rugby World Cup", Abbreviation: "RWC"},
	"180659":                      {Name: "Six Nations", Abbreviation: "6N"},
	"244293":                      {Name: "The Rugby Championship", Abbreviation: "TRC"},
	"271937":                      {Name: "European Rugby Champions Cup", Abbreviation: "EPCR"},
	"272073":                      {Name: "European Rugby Challenge Cup", Abbreviation: "ERCC"},
	"267979":                      {Name: "Gallagher Premiership", Abbreviation: "PREM"},
	"270557":                      {Name: "United Rugby Championship", Abbreviation: "URC"},
	"270559":                      {Name: "French Top 14", Abbreviation: "TOP14"},
	"2009":                        {Name: "URBA Primera A", Abbreviation: "URBA"},
	"242041":                      {Name: "Super Rugby Pacific", Abbreviation: "SRP"},
	"289271":                      {Name: "Super Rugby Aotearoa", Abbreviation: "SRA"},
	"289272":                      {Name: "Super Rugby AU", Abbreviation: "SRAU"},
	"289277":                      {Name: "Super Rugby Trans-Tasman", Abbreviation: "SRTT"},
	"289279":                      {Name: "URBA Top 12", Abbreviation: "T12"},
	"270555":                      {Name: "Currie Cup", Abbreviation: "CC"},
	"270563":                      {Name: "Mitre 10 Cup", Abbreviation: "M10"},
	"236461":                      {Name: "Anglo-Welsh Cup", Abbreviation: "AWC"},
	"289274":                      {Name: "2020 Tri Nations", Abbreviation: "TN"},
	"282":                         {Name: "Olympic Men's 7s", Abbreviation: "OLY"},
	"283":                         {Name: "Olympic Women's Rugby Sevens", Abbreviation: "OLY"},
	"289237":                      {Name: "Women's Rugby World Cup", Abbreviation: "WRWC"},
	"289262":                      {Name: "Major League Rugby", Abbreviation: "MLR"},
	"289234":                      {Name: "International Test Match", Abbreviation: "INT"},
	"3":                           {Name: "Rugby League", Abbreviation: "RL"},
	"fifa.world":                  {Name: "FIFA World Cup", Abbreviation: "WC"},
	"fifa.wwc":                    {Name: "FIFA Women's World Cup", Abbreviation: "WWC"},
	"uefa.champions":              {Name: "UEFA Champions League", Abbreviation: "UCL"},
	"eng.1":                       {Name: "English Premier League", Abbreviation: "EPL"},
	"eng.fa":                      {Name: "English FA Cup", Abbreviation: "FAC"},
	"eng.league_cup":              {Name: "English Carabao Cup", Abbreviation: "ELC"},
	"esp.1":                       {Name: "Spanish LALIGA", Abbreviation: "LIGA"},
	"esp.super_cup":               {Name: "Spanish Supercopa", Abbreviation: "SC"},
	"esp.copa_del_rey":            {Name: "Spanish Copa del Rey", Abbreviation: "CDR"},
	"ger.1":                       {Name: "German Bundesliga", Abbreviation: "BUN"},
	"ger.dfb_pokal":               {Name: "German Cup", Abbreviation: "DFB"},
	"usa.1":                       {Name: "MLS", Abbreviation: "MLS"},
	"concacaf.leagues.cup":        {Name: "Leagues Cup", Abbreviation: "LC"},
	"campeones.cup":               {Name: "Campeones Cup", Abbreviation: "CC"},
	"fifa.shebelieves":            {Name: "SheBelieves Cup", Abbreviation: "SBC"},
	"fifa.w.champions_cup":        {Name: "FIFA Women's Champions Cup", Abbreviation: "WCC"},
	"uefa.wchampions":             {Name: "UEFA Women's Champions League", Abbreviation: "UWCL"},
	"usa.nwsl":                    {Name: "NWSL", Abbreviation: "NWSL"},
	"usa.nwsl.cup":                {Name: "NWSL Challenge Cup", Abbreviation: "NWSLCC"},
	"uefa.europa":                 {Name: "UEFA Europa League", Abbreviation: "UEL"},
	"uefa.europa.conf":            {Name: "UEFA Conference League", Abbreviation: "UECL"},
	"mex.1":                       {Name: "Mexican Liga BBVA MX", Abbreviation: "LIGAMX"},
	"ita.1":                       {Name: "Italian Serie A", Abbreviation: "SA"},
	"ita.coppa_italia":            {Name: "Coppa Italia", Abbreviation: "CI"},
	"fra.1":                       {Name: "French Ligue 1", Abbreviation: "L1"},
	"atp":                         {Name: "ATP", Abbreviation: "ATP"},
	"wta":                         {Name: "WTA", Abbreviation: "WTA"},
	"mens-college-volleyball":     {Name: "NCAA Men's Volleyball", Abbreviation: "NCAMV"},
	"womens-college-volleyball":   {Name: "NCAA Women's Volleyball", Abbreviation: "NCAWV"},
	"mens-college-water-polo":     {Name: "NCAA Men's Water Polo", Abbreviation: "NCAMWP"},
	"womens-college-water-polo":   {Name: "NCAA Women's Water Polo", Abbreviation: "NCAWWP"},
}
